replicaCount: 2

image:
  repository: thepinkpanther96/r-m-api-k8s-pipline
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 5002

ingress:
  enabled: true
  className: nginx
  host: "rick-n-morty.local"

resources: {}