replicaCount: 2

image:
  repository: thepinkpanther96/r-m-api-k8s-pipline
  tag: v1.0
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 5010

ingress:
  enabled: true
  className: nginx
  host: "rick-n-morty.local"

resources: {}