name: k8s-deploy-and-test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      # Verify Docker is installed
      - name: Verify Docker
        run: docker version

      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          minikube start --driver=docker --wait=all
          minikube update-context

      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Debug step to ensure Chart.yaml is present
      - name: Debug - list helm chart files
        run: ls -al ./helm/rick-n-morty

      - name: Helm Install
        run: |
          helm install rick-n-morty ./helm/rick-n-morty --wait --timeout 120s

      - name: Get Pods
        run: kubectl get pods -o wide

      - name: Get Services
        run: kubectl get svc

      - name: Get Ingress
        run: kubectl get ingress

      - name: Port Forward
        run: nohup kubectl port-forward svc/rick-n-morty-rick-n-morty 5002:80 &

      - name: Wait
        run: sleep 10

      - name: Check Health Endpoint
        run: curl -f http://localhost:5002/healthcheck

      - name: Check Characters Endpoint
        run: curl -f http://localhost:5002/characters

      - name: Install test dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r tests/requirements.txt

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest tests/ --maxfail=1 --disable-warnings -v