name: K8s Test 

on:
  workflow_run:
    workflows: ["Docker Image CI Pipeline"]
    types:
      - completed

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          memory: 5002
          cpus: 2

      - name: Enable Minikube Ingress
        run: minikube addons enable ingress

      - name: Install kubectl and helm
        uses: yokawasa/action-setup-kube-tools@v0.11.2
        with:
          setup-tools: |
            kubectl
            helm
          kubectl: '1.25.0'
          helm: '3.11.1'

      - name: Wait for Ingress Controller
        run: |
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=300s

          if kubectl get job -n ingress-nginx | grep ingress-nginx-admission; then
            for job in $(kubectl get jobs -n ingress-nginx -o jsonpath='{.items[*].metadata.name}' | grep admission); do
              kubectl wait --for=condition=complete job/$job -n ingress-nginx --timeout=300s
            done
          fi

          sleep 20

      - name: Helm install application
        run: helm install rick-n-morty ./helm/rick-n-morty --set ingress.enabled=true #--wait --timeout 60s
    
      - name: Wait for Pods to be Ready
        run: |
          kubectl wait --for=condition=ready pod -l app=rick-n-morty --timeout=300s
          # Or check actual labels set by your chart
  
      - name: Get services
        run: kubectl get svc --all-namespaces
  
      - name: Port forward service
        run: kubectl port-forward svc/rick-n-morty-rick-n-morty 5002:80 &
  
      - name: Sleep
        run: sleep 10
     
      - name: Test characters endpoint
        run: curl -f http://localhost:5002/characters_data

      - name: Sleep
        run: sleep 10

      - name: Test healthcheck endpoint
        run: curl -f http://localhost:5002/healthcheck